 const GET_ALLVIDEOGAMES = "GET_ALLVIDEOGAMES",
  GET_VIDEOGAMES_BY_NAME = "GET_VIDEOGAMES_BY_NAME",
  GET_VIDEOGAMES_BY_ID = "GET_VIDEOGAMES_BY_ID",
  GET_GENRES = "GET_GENRES",
  ORDER_A = "ORDER_A",
  ORDER_R = "ORDER_R",
  FILTER_BY_GENRE = "FILTER_BY_GENRE",
  FILTER_BY_CREATED = "FILTER_BY_CREATED",
  CLEAR = "CLEAR",
  CREATE = "CREATE",
  GET_PLATFORMS = "GET_PLATFORMS";



module.exports = {
    GET_ALLVIDEOGAMES,
    GET_VIDEOGAMES_BY_NAME,
    GET_VIDEOGAMES_BY_ID,
    GET_GENRES,
    ORDER_A,
    ORDER_R,
    FILTER_BY_GENRE,
    FILTER_BY_CREATED,
    CLEAR,
    CREATE,
    GET_PLATFORMS
}
